### ISSUE TITLE
Values extending beyond table bounds

### ISSUE THREAD

**Issue by JordanGibson** [JordanGibson/ConsoleExtensions#1]
In certain scenarios (for example, the only item in "testStrings"), when the table is printed the value will extend beyond the bounds of the table. This is to do with how the escapeChar value is inserted in different strings. The order of insertion goes if a new line can be inserted between a space in the sentence -> if the word is too long, insert a new line in the middle of the current word and add a hyphen. The second stage is causing the problem. (Inside ConsoleTable.cs)
Screenshot: http://prntscr.com/lo8iy7

**Comment by JamesMatchett** [comment]
I'll hop on this, love a wee for-loop issue
